site_name: Device Manager
repo_url: https://github.com/Curso-de-Robotica-e-IA/device_manager
repo_name: RRIA/device_manager
edit_uri: tree/documentation/docs
nav:
  - Home: index.md
  - Usage: usage.md
  - Code: 
    - Base Classes: code/code_index.md
    - Connection Classes: code/connection.md

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  palette:
  # Palette toggle for manual mode
    - scheme: default
      primary: white
      toggle:
        icon: material/toggle-switch
        name: Dark Mode

  # Palette toggle for manual mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Light Mode

plugins:
- search
- offline
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          show_source: false

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css